apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    uid: TimescaleDB
    url: timescaledb:5432
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      database: ${POSTGRES_DB}
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: true
    isDefault: false
    editable: true
    version: 1
