'use strict';

const logger = require('./logger');

/**
 * SAP Prometheus Exporter — Dedicated T-Code JSON Parser
 * ======================================================
 *
 * Each SAP T-Code gets its own collector function that interprets the JSON data
 * and produces meaningful Prometheus metrics.
 *
 * IMPORTANT: Field names below were VERIFIED from actual S3 JSON payloads
 * by examining Prometheus metric names generated by the collector.
 *
 * Design principles:
 *   1. NO generic tree-walker — every metric is intentionally emitted
 *   2. Each T-Code collector knows the exact SAP data structure
 *   3. Supports uppercase (SM12/SM50/AL08) and lowercase (ST22) JSON fields
 *   4. No duplicate metric names with different label sets (causes Prometheus errors)
 */

// ── Helpers ──────────────────────────────────────────────────────────────

function labelVal(val) {
  if (val === undefined || val === null) return '';
  return String(val).substring(0, 128);
}

function countWhere(rows, predicate) {
  let c = 0;
  for (const r of rows) { if (predicate(r)) c++; }
  return c;
}

function freqMap(rows, fields) {
  const fieldList = Array.isArray(fields) ? fields : [fields];
  const m = new Map();
  for (const row of rows) {
    let raw = undefined;
    for (const f of fieldList) {
      if (row[f] !== undefined && row[f] !== null && row[f] !== '') {
        raw = row[f];
        break;
      }
    }
    if (raw === undefined || raw === null || raw === '') continue;
    const v = labelVal(raw);
    m.set(v, (m.get(v) || 0) + 1);
  }
  return m;
}

function sumField(rows, fields) {
  const fieldList = Array.isArray(fields) ? fields : [fields];
  let total = 0;
  for (const row of rows) {
    for (const f of fieldList) {
      const raw = row[f];
      if (raw === undefined || raw === null) continue;
      const n = parseFloat(String(raw).trim());
      if (!Number.isNaN(n) && Number.isFinite(n)) {
        total += n;
        break;
      }
    }
  }
  return parseFloat(total.toFixed(3));
}

function extractRows(parsed, tcode) {
  const ARRAY_KEYS = {
    AL08: ['data', 'DATA', 'sessions', 'SESSIONS', 'users', 'USERS', 'entries'],
    SM12: ['data', 'DATA', 'locks', 'LOCKS', 'entries'],
    SM50: ['data', 'DATA', 'work_processes', 'WORK_PROCESSES', 'workProcesses', 'wps', 'WPS', 'entries'],
    ST22: ['data', 'DATA', 'dumps', 'DUMPS', 'dump', 'st22_records', 'ST22_RECORDS', 'records', 'RECORDS', 'entries'],
  };

  const keys = ARRAY_KEYS[tcode] || ['data', 'DATA', 'entries'];
  for (const key of keys) {
    const arr = parsed[key];
    if (Array.isArray(arr) && arr.length > 0) {
      return arr;
    }
  }
  return [];
}

// ── T-Code Collectors ────────────────────────────────────────────────────

/**
 * AL08 — Logged-On Users
 * Actual JSON fields: CLIENT, USERID, TCODE, TERMINAL, TIME, HOSTADR, TYPE
 */
function collectAL08(rows, prefix) {
  const results = [];
  const n = rows.length;
  if (n === 0) return results;

  const uniqueUsers = new Set(rows.map((r) => r.USERID || r.USER || r.BNAME || ''));
  results.push({ fullName: `${prefix}_al08_logged_users`, value: uniqueUsers.size, labels: {} });
  results.push({ fullName: `${prefix}_al08_total_sessions`, value: n, labels: {} });
  results.push({ fullName: `${prefix}_al08_gui_users`, value: countWhere(rows, (r) => (r.TYPE || 'A') === 'A'), labels: {} });
  results.push({ fullName: `${prefix}_al08_background_users`, value: countWhere(rows, (r) => r.TYPE === 'B'), labels: {} });
  results.push({ fullName: `${prefix}_al08_rfc_users`, value: countWhere(rows, (r) => r.TYPE === 'C'), labels: {} });

  for (const [client, cnt] of freqMap(rows, 'CLIENT'))
    results.push({ fullName: `${prefix}_al08_client_count`, value: cnt, labels: { client } });
  for (const [tcode, cnt] of freqMap(rows, 'TCODE'))
    results.push({ fullName: `${prefix}_al08_tcode_count`, value: cnt, labels: { tcode } });
  for (const [user, cnt] of freqMap(rows, 'USERID'))
    results.push({ fullName: `${prefix}_al08_user_count`, value: cnt, labels: { user } });
  for (const [term, cnt] of freqMap(rows, 'TERMINAL'))
    results.push({ fullName: `${prefix}_al08_terminal_count`, value: cnt, labels: { terminal: term } });
  for (const [host, cnt] of freqMap(rows, 'HOSTADR'))
    results.push({ fullName: `${prefix}_al08_host_count`, value: cnt, labels: { host } });

  return results;
}

/**
 * SM12 — Lock Entries
 * Actual JSON fields: table, gmod, user_id, gclient, lock_arg
 */
function collectSM12(rows, prefix) {
  const results = [];
  const n = rows.length;
  if (n === 0) return results;

  results.push({ fullName: `${prefix}_sm12_total_locks`, value: n, labels: {} });

  const uniqueUsers = new Set(rows.map((r) => r.USER_ID || r.user_id || r.USER || r.BNAME || r.USER_NAME || ''));
  results.push({ fullName: `${prefix}_sm12_unique_users`, value: uniqueUsers.size, labels: {} });

  const uniqueTables = new Set(rows.map((r) => r.TABLE || r.table || r.TABNAME || r.TABLE_NAME || ''));
  results.push({ fullName: `${prefix}_sm12_locked_tables`, value: uniqueTables.size, labels: {} });

  // Exclusive locks (GMOD/gmod 'E' or 'X')
  results.push({
    fullName: `${prefix}_sm12_exclusive_locks`,
    value: countWhere(rows, (r) => {
      const mode = r.GMOD || r.gmod || r.LOCK_MODE || '';
      return mode === 'E' || mode === 'X';
    }),
    labels: {},
  });

  // Shared locks (GMOD/gmod 'S')
  results.push({
    fullName: `${prefix}_sm12_shared_locks`,
    value: countWhere(rows, (r) => (r.GMOD || r.gmod || r.LOCK_MODE || '') === 'S'),
    labels: {},
  });

  for (const [table, cnt] of freqMap(rows, ['TABLE', 'table', 'TABNAME', 'TABLE_NAME']))
    results.push({ fullName: `${prefix}_sm12_table_count`, value: cnt, labels: { table } });
  for (const [user, cnt] of freqMap(rows, ['USER_ID', 'user_id', 'USER', 'BNAME']))
    results.push({ fullName: `${prefix}_sm12_user_count`, value: cnt, labels: { user } });
  for (const [mode, cnt] of freqMap(rows, ['GMOD', 'gmod', 'LOCK_MODE']))
    results.push({ fullName: `${prefix}_sm12_lock_mode_count`, value: cnt, labels: { lock_mode: mode } });
  for (const [client, cnt] of freqMap(rows, ['GCLIENT', 'gclient', 'CLIENT']))
    results.push({ fullName: `${prefix}_sm12_client_count`, value: cnt, labels: { client } });

  return results;
}

/**
 * SM50 — Work Processes
 * Actual JSON fields: wp_status, wp_typ, wp_bname, wp_cpu, wp_client, wp_no, wp_report
 */
function collectSM50(rows, prefix) {
  const results = [];
  const n = rows.length;
  if (n === 0) return results;

  results.push({ fullName: `${prefix}_sm50_total_wp`, value: n, labels: {} });

  results.push({
    fullName: `${prefix}_sm50_running_wp`,
    value: countWhere(rows, (r) => {
      const s = r.WP_STATUS || r.wp_status || r.STATUS || '';
      return s === 'Running' || s === 'running' || s === 'RUNNING';
    }),
    labels: {},
  });

  results.push({
    fullName: `${prefix}_sm50_waiting_wp`,
    value: countWhere(rows, (r) => {
      const s = r.WP_STATUS || r.wp_status || r.STATUS || '';
      return s === 'Waiting' || s === 'waiting' || s === 'WAITING';
    }),
    labels: {},
  });

  results.push({
    fullName: `${prefix}_sm50_finished_wp`,
    value: countWhere(rows, (r) => {
      const s = r.WP_STATUS || r.wp_status || r.STATUS || '';
      return s === 'Finished' || s === 'finished' || s === 'FINISHED';
    }),
    labels: {},
  });

  results.push({
    fullName: `${prefix}_sm50_dialog_wp`,
    value: countWhere(rows, (r) => {
      const t = r.WP_TYP || r.wp_typ || r.TYPE || r.WP_TYPE || '';
      return t === 'DIA';
    }),
    labels: {},
  });

  results.push({
    fullName: `${prefix}_sm50_background_wp`,
    value: countWhere(rows, (r) => {
      const t = r.WP_TYP || r.wp_typ || r.TYPE || r.WP_TYPE || '';
      return t === 'BTC';
    }),
    labels: {},
  });

  results.push({
    fullName: `${prefix}_sm50_update_wp`,
    value: countWhere(rows, (r) => {
      const t = r.WP_TYP || r.wp_typ || r.TYPE || r.WP_TYPE || '';
      return t === 'UPD';
    }),
    labels: {},
  });

  results.push({
    fullName: `${prefix}_sm50_spool_wp`,
    value: countWhere(rows, (r) => {
      const t = r.WP_TYP || r.wp_typ || r.TYPE || r.WP_TYPE || '';
      return t === 'SPO';
    }),
    labels: {},
  });

  results.push({
    fullName: `${prefix}_sm50_enqueue_wp`,
    value: countWhere(rows, (r) => {
      const t = r.WP_TYP || r.wp_typ || r.TYPE || r.WP_TYPE || '';
      return t === 'ENQ';
    }),
    labels: {},
  });

  results.push({
    fullName: `${prefix}_sm50_stopped_wp`,
    value: countWhere(rows, (r) => {
      const s = r.WP_STATUS || r.wp_status || r.STATUS || '';
      return s === 'Stopped' || s === 'stopped' || s === 'STOPPED';
    }),
    labels: {},
  });

  // CPU seconds per type
  const types = ['DIA', 'BTC', 'UPD', 'SPO', 'ENQ'];
  for (const t of types) {
    const typeRows = rows.filter((r) => {
      const wt = r.WP_TYP || r.wp_typ || r.TYPE || r.WP_TYPE || '';
      return wt === t;
    });
    if (typeRows.length > 0) {
      const cpu = sumField(typeRows, ['WP_CPU', 'wp_cpu', 'CPU', 'CPU_TIME']);
      results.push({ fullName: `${prefix}_sm50_cpu_seconds`, value: cpu, labels: { type: t } });
    }
  }

  for (const [status, cnt] of freqMap(rows, ['WP_STATUS', 'wp_status', 'STATUS']))
    results.push({ fullName: `${prefix}_sm50_status_count`, value: cnt, labels: { status } });
  for (const [type, cnt] of freqMap(rows, ['WP_TYP', 'wp_typ', 'TYPE', 'WP_TYPE']))
    results.push({ fullName: `${prefix}_sm50_type_count`, value: cnt, labels: { type } });
  for (const [user, cnt] of freqMap(rows, ['WP_BNAME', 'wp_bname', 'USER', 'BNAME']))
    results.push({ fullName: `${prefix}_sm50_user_count`, value: cnt, labels: { user } });
  for (const [client, cnt] of freqMap(rows, ['WP_CLIENT', 'wp_client', 'CLIENT']))
    results.push({ fullName: `${prefix}_sm50_client_count`, value: cnt, labels: { client } });

  return results;
}

/**
 * ST22 — ABAP Runtime Errors (Dumps)
 * Actual JSON fields (can be lowercase): dumpid, programname, syuser, syhost, sydate, syclient, sycode, syline, errtype, errtext
 */
function collectST22(rows, prefix) {
  const results = [];
  const n = rows.length;
  if (n === 0) return results;

  results.push({ fullName: `${prefix}_st22_total_dumps`, value: n, labels: {} });

  const today = new Date();
  const todayStr = `${today.getFullYear()}${String(today.getMonth() + 1).padStart(2, '0')}${String(today.getDate()).padStart(2, '0')}`;
  const todayDumps = countWhere(rows, (r) => {
    const d = r.sydate || r.DATE || r.DATUM || r.SYDATE || '';
    return d === todayStr || d.startsWith(todayStr);
  });
  results.push({ fullName: `${prefix}_st22_today_dumps`, value: todayDumps, labels: {} });

  results.push({
    fullName: `${prefix}_st22_critical_dumps`,
    value: countWhere(rows, (r) => {
      const crit = r.CRITICAL || r.IS_CRITICAL || r.SEVERITY || '';
      return crit === 'X' || crit === 'true' || crit === 'CRITICAL' || crit === '1';
    }),
    labels: {},
  });

  for (const [dtype, cnt] of freqMap(rows, ['errtype', 'DUMP_TYPE', 'EXCEPT_NAME', 'TYPE']))
    results.push({ fullName: `${prefix}_st22_dump_type_count`, value: cnt, labels: { dump_type: dtype } });
  for (const [prog, cnt] of freqMap(rows, ['programname', 'PROGRAM', 'PROG']))
    results.push({ fullName: `${prefix}_st22_program_count`, value: cnt, labels: { program: prog } });
  for (const [user, cnt] of freqMap(rows, ['syuser', 'USER', 'BNAME']))
    results.push({ fullName: `${prefix}_st22_user_count`, value: cnt, labels: { user } });
  for (const [host, cnt] of freqMap(rows, ['syhost', 'HOST', 'SERVER']))
    results.push({ fullName: `${prefix}_st22_host_count`, value: cnt, labels: { host } });
  for (const [client, cnt] of freqMap(rows, ['syclient', 'CLIENT', 'MANDT']))
    results.push({ fullName: `${prefix}_st22_client_count`, value: cnt, labels: { client } });
  for (const [code, cnt] of freqMap(rows, ['sycode', 'ERROR_CLASS', 'EXCEPT']))
    results.push({ fullName: `${prefix}_st22_error_code_count`, value: cnt, labels: { error_code: code } });

  return results;
}

/**
 * ST06 — System Performance
 * Actual JSON structure (SAP ST06 export):
 * {
 *   "cpu": { "0": { "user_cpu": 5.2, "sys_cpu": 1.1, "idle_cpu": 93.7, "wait_true": 0.0, ... }, ... },
 *   "memory": { "0": { "avg_fr_mem": ..., "avg_swapfr": ..., "avg_swapsz": ..., ... }, ... },
 *   "disk": { "0": { "avg_util": ..., "avg_queuel": ..., "avg_servic": ..., ... }, ... },
 *   "lan":   { "0": { "in_packets": ..., "out_packet": ..., "errors": ..., ... }, ... }
 * }
 *
 * NOTE: Only averaged metrics are emitted (no per-core labels) to avoid
 * Prometheus label registration conflicts. Use avg() in Grafana queries.
 */
function collectST06(parsed, prefix) {
  const results = [];

  // ── CPU ──
  // First, check if parsed is an array (SAP sometimes wraps data in [])  
  const root = Array.isArray(parsed) ? (parsed[0] || parsed) : parsed;

  // Actual field names from SAP ST06 (camelCase): userCpu, sysCpu, idleCpu, waitTrue
  // The structure is: root.cpu.{n}.{userCpu, sysCpu, idleCpu, waitTrue, ...}
  const cpu = root.cpu || root.CPU || {};
  const cpuCores = Object.values(cpu).filter((v) => typeof v === 'object' && v !== null);

  if (cpuCores.length > 0) {
    let totalUser = 0, totalSys = 0, totalIdle = 0, totalWait = 0;
    for (const core of cpuCores) {
      totalUser += parseFloat(core.userCpu || core.user_cpu || core.USER_CPU || core.user || 0);
      totalSys += parseFloat(core.sysCpu || core.sys_cpu || core.SYS_CPU || core.system || 0);
      totalIdle += parseFloat(core.idleCpu || core.idle_cpu || core.IDLE_CPU || core.idle || 0);
      totalWait += parseFloat(core.waitTrue || core.wait_true || core.WAIT_TRUE || core.wait || 0);
    }
    const count = cpuCores.length;
    results.push({ fullName: `${prefix}_st06_cpu_user`, value: parseFloat((totalUser / count).toFixed(2)), labels: {} });
    results.push({ fullName: `${prefix}_st06_cpu_system`, value: parseFloat((totalSys / count).toFixed(2)), labels: {} });
    results.push({ fullName: `${prefix}_st06_cpu_idle`, value: parseFloat((totalIdle / count).toFixed(2)), labels: {} });
    results.push({ fullName: `${prefix}_st06_cpu_wait`, value: parseFloat((totalWait / count).toFixed(2)), labels: {} });
  } else {
    results.push({ fullName: `${prefix}_st06_cpu_user`, value: parseFloat(cpu.userCpu || cpu.user_cpu || root.cpu_user || 0), labels: {} });
    results.push({ fullName: `${prefix}_st06_cpu_system`, value: parseFloat(cpu.sysCpu || cpu.sys_cpu || root.cpu_system || 0), labels: {} });
    results.push({ fullName: `${prefix}_st06_cpu_idle`, value: parseFloat(cpu.idleCpu || cpu.idle_cpu || root.cpu_idle || 0), labels: {} });
    results.push({ fullName: `${prefix}_st06_cpu_wait`, value: parseFloat(cpu.waitTrue || cpu.wait_true || root.cpu_wait || 0), labels: {} });
  }

  // ── Memory ──
  // Actual fields (camelCase): avgFrMem, avgSwapsz, avgSwapfr, inPgHour, outPgHou
  const mem = root.memory || root.MEMORY || {};
  const memCores = Object.values(mem).filter((v) => typeof v === 'object' && v !== null);
  if (memCores.length > 0) {
    let totalFreeMem = 0, totalSwapSize = 0, totalSwapFree = 0, totalPgIn = 0, totalPgOut = 0;
    for (const core of memCores) {
      totalFreeMem += parseFloat(core.avgFrMem || core.avg_fr_mem || core.AVG_FR_MEM || 0);
      totalSwapSize += parseFloat(core.avgSwapsz || core.avg_swapsz || core.AVG_SWAPSZ || 0);
      totalSwapFree += parseFloat(core.avgSwapfr || core.avg_swapfr || core.AVG_SWAPFR || 0);
      totalPgIn += parseFloat(core.inPgHour || core.in_pg_hour || core.IN_PG_HOUR || 0);
      totalPgOut += parseFloat(core.outPgHou || core.out_pg_hou || core.OUT_PG_HOU || 0);
    }
    const count = memCores.length;
    results.push({ fullName: `${prefix}_st06_memory_free_avg`, value: parseFloat((totalFreeMem / count).toFixed(2)), labels: {} });
    results.push({ fullName: `${prefix}_st06_swap_size_avg`, value: parseFloat((totalSwapSize / count).toFixed(2)), labels: {} });
    results.push({ fullName: `${prefix}_st06_swap_free_avg`, value: parseFloat((totalSwapFree / count).toFixed(2)), labels: {} });
    results.push({ fullName: `${prefix}_st06_page_in_rate`, value: parseFloat((totalPgIn / count).toFixed(2)), labels: {} });
    results.push({ fullName: `${prefix}_st06_page_out_rate`, value: parseFloat((totalPgOut / count).toFixed(2)), labels: {} });
  }

  // ── Disk ──
  // Actual fields: avg_util, avg_queuel, avg_servic, avg_wait
  const disk = root.disk || root.DISK || {};
  const diskCores = Object.values(disk).filter((v) => typeof v === 'object' && v !== null);
  if (diskCores.length > 0) {
    let totalUtil = 0, totalQueue = 0, totalService = 0, totalWait = 0;
    for (const core of diskCores) {
      totalUtil += parseFloat(core.avgUtil || core.avg_util || core.AVG_UTIL || core.utilization || 0);
      totalQueue += parseFloat(core.avgQueuel || core.avg_queuel || core.AVG_QUEUEL || core.queue_length || 0);
      totalService += parseFloat(core.avgServic || core.avg_servic || core.AVG_SERVIC || 0);
      totalWait += parseFloat(core.avgWait || core.avg_wait || core.AVG_WAIT || 0);
    }
    const count = diskCores.length;
    results.push({ fullName: `${prefix}_st06_disk_utilization`, value: parseFloat((totalUtil / count).toFixed(2)), labels: {} });
    results.push({ fullName: `${prefix}_st06_disk_queue_length`, value: parseFloat((totalQueue / count).toFixed(2)), labels: {} });
    results.push({ fullName: `${prefix}_st06_disk_service_time`, value: parseFloat((totalService / count).toFixed(2)), labels: {} });
    results.push({ fullName: `${prefix}_st06_disk_wait_time`, value: parseFloat((totalWait / count).toFixed(2)), labels: {} });
  } else {
    results.push({ fullName: `${prefix}_st06_disk_utilization`, value: parseFloat(disk.avg_util || root.disk_utilization || 0), labels: {} });
    results.push({ fullName: `${prefix}_st06_disk_queue_length`, value: parseFloat(disk.avg_queuel || root.disk_queue_length || 0), labels: {} });
  }

  // ── LAN / Network ──
  // Actual fields: in_packets, out_packet, errors, collisions
  const lan = root.lan || root.LAN || root.network || root.NETWORK || {};
  const lanCores = Object.values(lan).filter((v) => typeof v === 'object' && v !== null);
  if (lanCores.length > 0) {
    let totalIn = 0, totalOut = 0, totalErrors = 0;
    for (const core of lanCores) {
      totalIn += parseInt(core.inPackets || core.in_packets || core.IN_PACKETS || core.in_bytes || 0, 10);
      totalOut += parseInt(core.outPacket || core.out_packet || core.OUT_PACKET || core.out_bytes || 0, 10);
      totalErrors += parseInt(core.errors || core.ERRORS || 0, 10);
    }
    const count = lanCores.length;
    if (totalIn > 0) results.push({ fullName: `${prefix}_st06_network_in_packets`, value: Math.round(totalIn / count), labels: {} });
    if (totalOut > 0) results.push({ fullName: `${prefix}_st06_network_out_packets`, value: Math.round(totalOut / count), labels: {} });
    if (totalErrors > 0) results.push({ fullName: `${prefix}_st06_network_errors`, value: Math.round(totalErrors / count), labels: {} });
  }

  return results;
}

// ── T-Code Collector Registry ────────────────────────────────────────────

const COLLECTOR_MAP = {
  AL08: collectAL08,
  SM12: collectSM12,
  SM50: collectSM50,
  ST22: collectST22,
  ST06: collectST06,
};

// ── Parser Entry Point ───────────────────────────────────────────────────

function parseToMetrics(jsonString, tcode, metricsPrefix) {
  const rawMetrics = [];
  let parseError = null;

  try {
    const parsed = JSON.parse(jsonString);
    const tcodeKey = tcode.toUpperCase();
    const collector = COLLECTOR_MAP[tcodeKey];
    if (collector) {
      if (tcodeKey === 'ST06') {
        const st06Metrics = collectST06(parsed, metricsPrefix);
        rawMetrics.push(...st06Metrics);
      } else {
        const rows = extractRows(parsed, tcodeKey);
        if (!Array.isArray(rows) || rows.length === 0) {
          // If no array found, try treating the entire object as a single record
          logger.warn({ tcode }, 'No data array found in JSON — checking for single-record format');
          // Some exporters may put the fields directly at top level (no data[] wrapper)
          const singleRecord = parsed;
          if (singleRecord && typeof singleRecord === 'object' && !Array.isArray(singleRecord)) {
            const tcMetrics = collector([singleRecord], metricsPrefix);
            rawMetrics.push(...tcMetrics);
          }
        } else {
          const tcMetrics = collector(rows, metricsPrefix);
          rawMetrics.push(...tcMetrics);
        }
      }
    } else {
      logger.warn({ tcode }, 'No dedicated collector registered — no metrics generated');
    }
  } catch (err) {
    parseError = err;
    logger.error({ err, tcode }, 'Failed to parse JSON for T-Code');
  }

  const metrics = rawMetrics.map((m) => ({
    fullName: m.fullName,
    value: m.value,
    labels: m.labels,
  }));

  logger.debug({ tcode, metricCount: metrics.length }, 'Parsed metrics from JSON');
  return { metrics, parseError };
}

module.exports = {
  parseToMetrics,
  collectAL08,
  collectSM12,
  collectSM50,
  collectST22,
  collectST06,
};
